version: "3"
services:
  backend:
    image: "array001/fil-rouge:v2"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/so_code?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - file-rouge-nt

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: so_code
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - file-rouge-nt

  frontend:
    image: array0001/front-app:v1
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - file-rouge-nt

networks:
  file-rouge-nt:
    driver: bridgev

volumes:
  mysql_data:


