spring:
  datasource:
    url: jdbc:mysql://localhost:3306/so_code?createDatabaseIfNotExist=true
    password:
    username: root
    initialization-mod: always
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
#    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081
#  spring.sql.init.mode=always
#  spring.datasource.initialization-mode=always